### PR TITLE
Fix auto expansion of custom data

### PR DESCRIPTION
**Pull request by erbridge**

### CODE REVIEW

**Comment by rdegges** [comment]
I pushed this fix in manually, as we did some big refactoring which would have broken the merge! Thanks! Will cut a release tomorrow.

**Comment by bassie1995** [comment]
This hasn't fixed the issue for me, it still gives me the Object with only an href in it.

**Comment by rdegges** [comment]
This release hasn't been cut yet, sorry! Adding in testing around it.

**Comment by bassie1995** [comment]
Thanks, will update when the release hits!

**Comment by bassie1995** [comment]
Is this in 2.0.9? It still doesn't seem to work for me.

**Comment by robertjd** [comment]
This *should* be fixed in 2.0.9, can you give me more context for your problem?  If you could share your code with me that would be really helpful.  If you don't want to share here you can contact us privately via support@stormpath.com

**Comment by bassie1995** [comment]
Yep, my app.js is as follows: 
https://gist.github.com/bassie1995/9feafbc4fb72166c00f8.

Tried to use just expandCustomData: true as well.

I'll be glad to provide more info.

**Comment by erbridge** [comment]
This is working for me now. I think you need:

```js
expand: {
  customData: true
}
```

not `expandCustomData: true`.

Also, you probably want to reset your API keys since they're completely exposed in that gist...

**Comment by bassie1995** [comment]
Huh, that did fix it. I have tried that (or something close, I guess) before, but I'm glad it works now.

I'll be resetting the keys once we go live, as well :)

**Pull request closed without merging**
