### PR TITLE
allow user to specify custom render handler

### PR DESCRIPTION
**Pull request by jmls**
app.use(stormpath.init(app, {
...
    renderHandler: function(view,res,options) {
      // custom render handling here - use jade, handlebars etc or just set some extra form options
    },
...
}

adding this option allows the developer to use their own view engine (jade / handlebars etc) when rendering any of the stormpath views. It also allows the developer to add / remove options before the view is rendered

### CODE REVIEW

**Comment by jmls** [comment]
any news on getting this integrated ? Or shall I just keep using the forked version ? Thanks

**Comment by rdegges** [comment]
Hey @jmls, thanks for this! Sorry it's taken so long to actually respond to this. 

We've been uber busy, and while it's no excuse, I'm finally getting around to merging all this awesome stuff in!

Thank you so much for the contribution <333

**Comment by rdegges** [comment]
No idea if you want to take a stab at it -- but if you do, I'd be totally happy to accept a PR for documenting this feature as well. Would be a cool addition.

If I don't hear back I'll throw in something myself next week =)

**Comment by rdegges** [comment]
Also: going to cut a release shortly with this included =)

**Pull request merged**
