### PR TITLE
fixed google plus integration

### PR DESCRIPTION
**Pull request by dgisser**
#118 This will fix issues with var next giving an error, especially since this variable is never used to begin with.

### CODE REVIEW

**Comment by rdegges** [comment]
Thanks! This makes sense. I think the original plan was to support redirection to the `?next=...` url with Google Login, but I don't think I found a way to do it using their API, so I left it half-implemented. Am happy to merge this in!

**Comment by robertjd** [comment]
Perhaps we should implement an option in our config, such as `socialProviders.google.nextUri` ? This would be similar to how we handle all of our other redirects, and gives us a way to declare a post-google-login redirect (without relying on their API).

**Comment by rdegges** [comment]
This has is specifically meant for people who want to hit a protected page, eg: `/secret`, then get redirected to login: `/login?next=%2Fsecret`, then log in with Google and get back to `/secret` automatically.

**Comment by robertjd** [comment]
Ah, thanks for clarification.

**Pull request merged**
